{% set name = "mindoptpy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win and not x86_64]
  missing_dso_whitelist:
    - /lib/libgcc_s.so.1
    - /lib64/ld-linux-x86-64.so.2
    - /lib64/libc.so.6
    - /lib64/libdl.so.2
    - /lib64/libm.so.6
    - /lib64/libpthread.so.0
    - /lib64/librt.so.1
    - $RPATH/libiomp5.so
    - $RPATH/libiomp5md.dll
    - $RPATH/mindopt.dll

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - mindoptpy

about:
  home: https://opt.aliyun.com/portal
  license: Commercial
  license_file: LICENSE
  summary: mindoptpy is a Python wrapper around mindopt with Cython.
  description: |
    MindOpt optimization solver is an efficient optimization problem solving software, 
    which can be widely used in scientific research, electric power and energy, 
    industrial manufacturing, transportation and logistics, retail, finance, 
    cloud computing and other fields. It is the core of industrial software and 
    a powerful tool to help enterprises "reduce cost and increase efficiency".
  doc_url: https://opt.aliyun.com/doc/latest/en/html/index.html

extra:
  recipe-maintainers:
    - buchengsyh
