{% set name = "mindoptpy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

requirements:
  build:
    skip: True  # [win and not x86_64]
    - python
  run:
    - python
    - numpy
    - scipy

test:
  commands:
    - pip check
  import:
    - mindoptpy

about:
  summary: mindoptpy is a Python wrapper around mindopt with Cython.
  description: |
    MindOpt optimization solver is an efficient optimization problem solving software, 
    which can be widely used in scientific research, electric power and energy, 
    industrial manufacturing, transportation and logistics, retail, finance, 
    cloud computing and other fields. It is the core of industrial software and 
    a powerful tool to help enterprises "reduce cost and increase efficiency".
  doc_url: https://opt.aliyun.com/doc/latest/en/html/index.html
